import { useCallback } from "react";
import type { OrchestrationResult } from "@/lib/designerAgent";

interface Props {
  projectName: string;
  projectType?: string;
  budget?: string | null;
  dimensions?: string;
  results: OrchestrationResult | null;
}

/** Generate a print-friendly spec sheet and trigger browser print dialog */
const ExportPdf = ({ projectName, projectType, budget, dimensions, results }: Props) => {
  const handleExport = useCallback(() => {
    if (!results) return;

    const renders = results.renders;
    const products = results.products;
    const sl = results.shoppingList;

    const renderImages = renders
      .map(
        (r) => `
        <div style="break-inside: avoid; margin-bottom: 16px;">
          <img src="${r.url}" alt="${r.label}" style="width: 100%; max-height: 300px; object-fit: cover; border: 1px solid #e0e0e0;" crossorigin="anonymous" />
          <p style="font-size: 11px; color: #666; margin-top: 4px;">${r.label} — ${r.style}</p>
        </div>`
      )
      .join("");

    const productRows = products
      .map(
        (p) => `
        <tr>
          <td style="padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px;">${p.name}</td>
          <td style="padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px; color: #666;">${p.brand}</td>
          <td style="padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px;">${p.category}</td>
          <td style="padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px; text-align: right;">$${p.price.toLocaleString()}</td>
        </tr>`
      )
      .join("");

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${projectName} — Specification Sheet</title>
        <style>
          @media print { body { margin: 0; } }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 32px; color: #1a1a1a; }
          h1 { font-size: 20px; font-weight: 600; margin-bottom: 4px; }
          h2 { font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; color: #666; margin-top: 32px; margin-bottom: 12px; border-bottom: 1px solid #e0e0e0; padding-bottom: 6px; }
          .meta { font-size: 11px; color: #888; font-family: monospace; }
          .meta span { margin-right: 16px; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; }
          th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #888; padding: 6px 8px; border-bottom: 2px solid #e0e0e0; }
          th:last-child { text-align: right; }
          .total-row td { font-weight: 600; border-top: 2px solid #1a1a1a; padding-top: 8px; }
          .footer { margin-top: 40px; font-size: 10px; color: #aaa; text-align: center; font-family: monospace; }
        </style>
      </head>
      <body>
        <h1>${projectName}</h1>
        <div class="meta">
          ${projectType ? `<span>Type: ${projectType}</span>` : ""}
          ${dimensions ? `<span>Dimensions: ${dimensions}</span>` : ""}
          ${budget ? `<span>Budget: ${budget}</span>` : ""}
          <span>Generated: ${new Date().toLocaleDateString()}</span>
        </div>

        ${renders.length > 0 ? `<h2>Design Renders</h2><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">${renderImages}</div>` : ""}

        ${products.length > 0 ? `
          <h2>Sourcing Specification</h2>
          <table>
            <thead><tr><th>Product</th><th>Brand</th><th>Category</th><th>Price</th></tr></thead>
            <tbody>
              ${productRows}
              ${sl ? `<tr class="total-row"><td colspan="3">${sl.item_count} items${sl.budget_remaining !== null ? ` · $${sl.budget_remaining.toLocaleString()} remaining` : ""}</td><td style="text-align: right;">$${sl.total.toLocaleString()}</td></tr>` : ""}
            </tbody>
          </table>
        ` : ""}

        <div class="footer">Generated by clawd·studio</div>
      </body>
      </html>
    `;

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }, [projectName, projectType, budget, dimensions, results]);

  return (
    <button
      onClick={handleExport}
      disabled={!results || (results.renders.length === 0 && results.products.length === 0)}
      className="h-[30px] px-3 gallery-border text-[12px] font-mono text-muted-foreground hover:text-foreground transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
      title="Export spec sheet as PDF"
    >
      Export PDF
    </button>
  );
};

export default ExportPdf;
